header:
  version: 15

repos:
  poky:
    url: https://git.yoctoproject.org/git/poky
    path: layers/poky
    branch: nanbield
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: layers/meta-openembedded
    branch: nanbield
    layers:
      meta-filesystems:
      meta-networking:
      meta-oe:
      meta-perl:
      meta-python:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    path: layers/meta-arm
    branch: nanbield
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-clang:
    url: https://github.com/kraj/meta-clang
    path: layers/meta-clang
    branch: nanbield

  meta-security:
    url: https://git.yoctoproject.org/meta-security
    path: layers/meta-security
    branch: nanbield

  meta-rauc:
    url: https://github.com/rauc/meta-rauc
    path: layers/meta-rauc
    branch: nanbield
